#ifndef METOCEANVIEWER_H
#define METOCEANVIEWER_H

namespace MetOceanViewer {

namespace FileType {
enum _filetype {
  NETCDF_ADCIRC,
  NETCDF_DFLOW,
  NETCDF_GENERIC,
  ASCII_ADCIRC,
  ASCII_IMEDS,
  FILETYPE_ERROR
};
};

namespace Error {
enum _error {
  NOERR,
  NOAA_INVALIDDATERANGE,
  USGS_SERVERREADERROR,
  USGS_ARCHIVEONLY,
  USGS_READDATA,
  USGS_FORMATTING,
  CANNOT_OPEN_FILE,
  WRONG_NUMBER_OF_STATIONS,
  NETCDF,
  NO_VARIABLE_FOUND,
  DFLOW_GETPLOTVARS,
  DFLOW_GETSTATIONS,
  DFLOW_NOXVELOCITY,
  DFLOW_NOYVELOCITY,
  DFLOW_NOZVELOCITY,
  DFLOW_3DVARS,
  DFLOW_VARNOTFOUND,
  DFLOW_ILLEGALDIMENSION,
  DFLOW_FILEREADERROR,
  ADCIRC_ASCIIREADERROR,
  ADCIRC_NETCDFREADERROR,
  IMEDS_FILEREADERROR,
  INVALIDFILEFORMAT,
  GENERICNETCDFERROR,
  GENERICFILEREADERROR,
  ADCIRC_ASCIITOIMEDS,
  ADCIRC_NETCDFTOIMEDS,
  BUILDSTATIONLIST,
  BUILDREVISEDIMEDS,
  PROJECTSTATIONS,
  MARKERSELECTION
};
};
} // namespace MetOceanViewer

#endif // METOCEANVIEWER_H
