#ifndef MOV_ERRORS_H
#define MOV_ERRORS_H

#define ERR_NOAA_INVALIDDATERANGE -9990
#define ERR_USGS_SERVERREADERROR  -8880
#define ERR_USGS_ARCHIVEONLY      -8881
#define ERR_USGS_READDATA         -8882
#define ERR_USGS_FORMATTING       -8883

#endif // ERRORS_H

